#!/usr/bin/env python -O -t -W all

import argparse
import sys
import os
import shutil
import src.iterator as iterator
import src.processStemOut as processStemOut
import src.parseBeast as parseBeast

# todo:
#    - determine default values of arguments
#    - actually run the scripts
#    - determine which combinations of arguments are required with others
#    - ability to handle multiple types of settings files/associations files
#    - find a better way to add src directory to path (for other os's as well)

def parseArgs():
    parser = argparse.ArgumentParser(\
        description='SpedeSTEM 2, a python package for species delimitation.', \
        epilog='For additional help see [this website]')

    subparsers = parser.add_subparsers(help='commands', dest='command')

    ########################### setup mode #############################
    setup_parser = subparsers.add_parser('setup', help='prepare tree and settings files for analysis')
    setup_parser.add_argument('-c', '--clean', metavar='treeFile', nargs='+', \
                              help='prepare tree file(s) for analysis')
    setup_parser.add_argument('-s', '--scalingFile', metavar='scalingFile', nargs=1, \
                              help='provide a text file with each scaling factor on a new line ' + \
                              'in the format: [scalingFactor]. Values prefixed in the order that ' + \
                              'trees appear after the clean command, DEFAULT: [1.0] for each', default=None)
    setup_parser.add_argument('-t', '--traits', metavar='traitsFile', nargs=1,
                              help='read in traits file as Beast format')
    setup_parser.add_argument('-bt', '--theta', type=float, metavar="thetaValue",
                              help='set theta value for beast formatted traits files, DEFAULT: 1.0', nargs=1, \
                              default=[1.0])


    ######################### discovery analysis mode ####################
    discovery_parser = subparsers.add_parser('discovery', help='discovery analysis')
    discovery_parser.add_argument('-t', '--tree', metavar='treeFile', nargs=1, required=True, \
                                  help='specify tree file')
    discovery_parser.add_argument('-s', '--settings', metavar='settingsFile', nargs=1, required=True, \
                                  help='specify settings file in STEM format')
    discovery_parser.add_argument('-v', '--verbose', action="store_true", help='execute in verbose mode, DEFAULT: off',
                                   default=False)


    ####################### validation analysis mode #######################
    validation_parser = subparsers.add_parser('validation', help='validation analysis')
    validation_parser.add_argument('-t', '--tree', metavar='treeFile', nargs=1, required=True, \
                                  help='specify tree file')
    validation_parser.add_argument('-s', '--settings', metavar='settingsFile', nargs=1, required=True, \
                                  help='specify settings file in STEM format')
    validation_parser.add_argument('-a', '--associations', metavar='associationsFile', nargs=1, required=True, \
                                   help='specify associations file in STEM format')
    validation_parser.add_argument('-v', '--verbose', action="store_true", help='execute in verbose mode, DEFAULT: off'
                                   , default=False)

    # subsampling mode
    subsampling_parser = subparsers.add_parser('subsampling', help='talk about subsampling')

    # testing mode
    testing_parser = subparsers.add_parser('testing', help='power testing')
    testing_parser.add_argument('-n', '--numtrees', metavar='numTrees', type=int, nargs=1, \
                                  help='number of trees to be sampled from each specified tree file, ' + \
                                  'DEFAULT: 1', default=[1])
    testing_parser.add_argument('-r', '--runs', metavar='numTimes', type=int, nargs=1, \
                                  help='execute the complete discovery analysis numTimes times,' +
                                  'taking numTimes samples of the tree file, DEFAULT: 1',
                                  default=[1])

    # restore
    restore_parser = subparsers.add_parser('restore', help='restore initial configuration, ' + \
                                           'WARNING: all results in project folder will be lost, ' + \
                                           'move files out of this directory to save them.')
    args = parser.parse_args()

    # catch invalid option configurations
    if args.command == 'setup' and args.scalingFile and not args.clean:
        setup_parser.error('Scaling factors specified without tree file, ' + \
                           'add --clean or remove --scalingFile')

    # print args
    return args

def executeChoice(args):
    if args.command == 'setup':
        ''' 
        Arguments (args.): 
            clean -> list of strings representing tree file names
            scalingFile -> string representing file name
            theta -> float value used when beast file is specified
            traits -> string representing beast formatted file
        '''
        print '\n################################'
        print '####### Performing Setup #######'
        print '################################\n'

        if args.clean:
            if args.scalingFile:
                scalingFile = args.scalingFile[0]
            # clean trees and prefix each with scaling factors if file provided
            cleanTrees.CleanTrees(args.clean, scalingFile, sigfigs=8)

        if args.traits:
            # convert beast formatted traits file to stem settings
            parseBeast.ParseBeast(settingsIn=args.traits[0], theta=args.theta[0])

        else:
            print "SpedeSTEM_2 setup: error: No options specified. Try '-h' for help"

    elif args.command == 'discovery':
        print '\n################################'
        print '###### DISCOVERY ANALYSIS ######'
        print '################################\n'

        # check here for settings file, tree files, maybe scan the files for correct formatting
        discovery = iterator.Iterator([args.tree], numRuns=1, \
                                      numTrees=None, settings=args.settings[0], maxTrees=None, \
                                      verbose=args.verbose)
        discovery.printSettings()
        discovery.run()

        # process the stem output
        print "Completing Analysis...",
        processor = processStemOut.ProcessStemOut()
        processor.rawOutput()
        processor.calculateWilik()
        print "See 'results.txt' and 'itTable.txt' files\n"

    elif args.command == 'validation':
        print '\n#################################'
        print '###### VALIDATION ANALYSIS ######'
        print '#################################\n'

        # check for settings, tree files, associations, etc.
        validation = iterator.Iterator([args.tree], numRuns=1, \
                                      numTrees=None, settings=args.settings[0], maxTrees=None, \
                                      verbose=args.verbose, isValidation=True, associations=args.associations[0])
        validation.printSettings()
        validation.run()

        # process the stem output
        print "Completing Analysis...",
        processor = processStemOut.ProcessStemOut()
        processor.rawOutput()
        processor.calculateWilik()
        print "See 'results.txt' and 'itTable.txt' files\n"

    elif args.command == 'testing':
        print 'Testing...'
    elif args.command == 'restore':
        print 'Restoring...'

def main():
    args = parseArgs()
    executeChoice(args)


if __name__ == '__main__':
    main()
